version: '2'
services:
  majakkamysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - data:/var/lib/mysql
    ports:
      - 7788:3306
      - 7789:3360
    networks:
      - majakkaportaali
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - majakkaportaali
  majakkaphp:
    build:
      context: ./
      dockerfile: container_files/majakkaphp.dockerfile
    volumes:
      - ./:/var/www/html/
    networks:
      - majakkaportaali
  gulp:
    image: node:10
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: "npm start"
  composer:
      image: composer
      volumes:
          - .:/app
      command: install
  majakkanginx:
    image: nginx:alpine
    depends_on:
        - majakkamysql
        - majakkaphp
    volumes:
        - ./container_files/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html/
    ports:
        - 8000:80
        - 3000:443
    networks:
      - majakkaportaali
volumes:
  data:
    driver: local
networks:
  majakkaportaali:
